version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tu_basedatos
      MYSQL_USER: userapp
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ../backend
    container_name: app_backend
    restart: always
    environment:
      DATABASE_URL: "mysql://userapp:userpass@db:3306/tu_basedatos"
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    build: ../frontend
    container_name: app_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend